version: '3'

services:

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
# postgresql://postgres:postgres@database:5432/postgres